# Generated by Django 4.0.4 on 2022-08-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('room_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('game_state', models.JSONField()),
                ('players', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tictactoe.playermodel')),
            ],
        ),
    ]
