# Generated by Django 4.0.4 on 2022-08-21 07:18

from django.db import migrations, models
import tictactoe.game.enums


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='room_state',
            field=models.IntegerField(choices=[(10, 'IN_LOBBY'), (20, 'GAME_START'), (21, 'GAME_IN_PROGRESS'), (30, 'GAME_ENDED'), (40, 'GAME_ABORTED')], default=tictactoe.game.enums.RoomState['IN_LOBBY']),
        ),
    ]
