# Generated by Django 4.0.4 on 2022-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_gamemodel_room_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='players',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='players',
            field=models.ManyToManyField(to='tictactoe.playermodel'),
        ),
    ]
