# Generated by Django 4.0.4 on 2022-08-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_remove_gamemodel_players_gamemodel_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermodel',
            old_name='player_name',
            new_name='name',
        ),
    ]
